/**
 * Static redirect mappings
 * Format: 'source-path': 'destination-path'
 *
 * For internal redirects, provide the path without domain
 * For external redirects, provide the full URL including protocol
 */
export const redirectMaps: Record<string, string> = {
  // Main section redirects
  'operator-guide': 'https://docs.kuberocketci.io/docs/operator-guide',
  'operator-guide/index': 'https://docs.kuberocketci.io/docs/operator-guide',
  'user-guide': 'https://docs.kuberocketci.io/docs/user-guide',
  'user-guide/index': 'https://docs.kuberocketci.io/docs/user-guide',
  'index': 'https://docs.kuberocketci.io',
  'overview': 'https://docs.kuberocketci.io/docs/about-platform',
  'features': 'https://docs.kuberocketci.io/docs/basic-concepts',
  'glossary': 'https://docs.kuberocketci.io/docs/glossary',
  'supported-versions': 'https://docs.kuberocketci.io/docs/supported-versions',
  'compliance': 'https://docs.kuberocketci.io/docs/compliance',
  'developer-guide': 'https://docs.kuberocketci.io/docs/developer-guide',
  'developer-guide/reference-architecture': 'https://docs.kuberocketci.io/docs/developer-guide/reference-architecture',
  'use-cases': 'https://docs.kuberocketci.io/docs/use-cases',

  // Operator guide redirects
  'operator-guide/installation-overview': 'https://docs.kuberocketci.io/docs/operator-guide/installation-overview',
  'operator-guide/add-ons-overview': 'https://docs.kuberocketci.io/docs/operator-guide/add-ons-overview',
  'operator-guide/prerequisites': 'https://docs.kuberocketci.io/docs/operator-guide/prerequisites',
  'operator-guide/kubernetes-cluster-settings': 'https://docs.kuberocketci.io/docs/operator-guide/kubernetes-cluster-settings',
  'operator-guide/openshift-cluster-settings': 'https://docs.kuberocketci.io/docs/operator-guide/openshift-cluster-settings',
  'operator-guide/install-ingress-nginx': 'https://docs.kuberocketci.io/docs/operator-guide/install-ingress-nginx',
  'operator-guide/install-argocd': 'https://docs.kuberocketci.io/docs/operator-guide/install-argocd',
  'operator-guide/install-tekton': 'https://docs.kuberocketci.io/docs/operator-guide/install-tekton',
  'operator-guide/install-edp': 'https://docs.kuberocketci.io/docs/operator-guide/install-kuberocketci',
  'operator-guide/aws-marketplace-install': 'https://docs.kuberocketci.io/docs/operator-guide/aws-marketplace-install',
  'operator-guide/install-via-civo': 'https://docs.kuberocketci.io/docs/operator-guide/install-via-civo',
  'operator-guide/advanced-installation-overview': 'https://docs.kuberocketci.io/docs/operator-guide/advanced-installation/overview',
  'operator-guide/install-harbor': 'https://docs.kuberocketci.io/docs/operator-guide/artifacts-management/harbor-installation',
  'operator-guide/capsule': 'https://docs.kuberocketci.io/docs/operator-guide/advanced-installation/capsule',
  'operator-guide/install-keycloak': 'https://docs.kuberocketci.io/docs/operator-guide/auth/keycloak',
  'operator-guide/install-defectdojo': 'https://docs.kuberocketci.io/docs/operator-guide/devsecops/defectdojo',
  'operator-guide/install-reportportal': 'https://docs.kuberocketci.io/docs/operator-guide/project-management-and-reporting/install-reportportal',
  'operator-guide/vcs': 'https://docs.kuberocketci.io/docs/user-guide/add-git-server',
  'operator-guide/headlamp-oidc': 'https://docs.kuberocketci.io/docs/operator-guide/auth/ui-portal-oidc',
  'operator-guide/namespace-management': 'https://docs.kuberocketci.io/docs/operator-guide/auth/namespace-management',
  'operator-guide/customize_deployment': 'https://docs.kuberocketci.io/docs/operator-guide/cd/customize-deploy-pipeline',
  'operator-guide/eks-oidc-integration': 'https://docs.kuberocketci.io/docs/operator-guide/auth/configure-keycloak-oidc-eks',
  'operator-guide/jira-integration': 'https://docs.kuberocketci.io/docs/operator-guide/project-management-and-reporting/jira-integration',
  'operator-guide/jira-gerrit-integration': 'https://docs.kuberocketci.io/docs/about-platform',
  'operator-guide/tekton-overview': 'https://docs.kuberocketci.io/docs/operator-guide/ci/tekton-overview',
  'operator-guide/tekton-monitoring': 'https://docs.kuberocketci.io/docs/operator-guide/ci/tekton-monitoring',
  'operator-guide/notification-msteams': 'https://docs.kuberocketci.io/docs/operator-guide/ci/notification-msteams',
  'operator-guide/container-registries': 'https://docs.kuberocketci.io/docs/user-guide/change-container-registry',
  'operator-guide/container-registry-harbor-integration-tekton-ci': 'https://docs.kuberocketci.io/docs/operator-guide/artifacts-management/harbor-integration',
  'operator-guide/harbor-oidc': 'https://docs.kuberocketci.io/docs/operator-guide/artifacts-management/harbor-oidc',
  'operator-guide/package-registry': 'https://docs.kuberocketci.io/docs/operator-guide/artifacts-management/package-registry',
  'operator-guide/waf-tf-configuration': 'https://docs.kuberocketci.io/docs/operator-guide/infrastructure-providers/aws/waf-tf-configuration',
  'operator-guide/ebs-csi-driver': 'https://docs.kuberocketci.io/docs/operator-guide/infrastructure-providers/aws/ebs-csi-driver',
  'operator-guide/enable-irsa': 'https://docs.kuberocketci.io/docs/operator-guide/infrastructure-providers/aws/enable-irsa',
  'operator-guide/velero-irsa': 'https://docs.kuberocketci.io/docs/operator-guide/disaster-recovery/velero-irsa',
  'operator-guide/loki-irsa': 'https://docs.kuberocketci.io/docs/operator-guide/monitoring-and-observability/loki-irsa',
  'operator-guide/configure-keycloak-oidc-eks': 'https://docs.kuberocketci.io/docs/operator-guide/auth/configure-keycloak-oidc-eks',
  'operator-guide/reportportal-keycloak': 'https://docs.kuberocketci.io/docs/operator-guide/project-management-and-reporting/reportportal-keycloak',
  'operator-guide/report-portal-integration-tekton': 'https://docs.kuberocketci.io/docs/operator-guide/project-management-and-reporting/reportportal-tekton',
  'operator-guide/logsight-integration': 'https://docs.kuberocketci.io/docs/about-platform',
  'operator-guide/dependency-track': 'https://docs.kuberocketci.io/docs/operator-guide/devsecops/dependency-track',
  'operator-guide/sonarqube': 'https://docs.kuberocketci.io/docs/operator-guide/code-quality/sonarqube',
  'operator-guide/sonarqube-visibility': 'https://docs.kuberocketci.io/docs/operator-guide/code-quality/sonarqube-visibility',
  'operator-guide/nexus-sonatype': 'https://docs.kuberocketci.io/docs/operator-guide/artifacts-management/nexus-sonatype',
  'operator-guide/argocd-integration': 'https://docs.kuberocketci.io/docs/operator-guide/cd/argocd-integration',
  'operator-guide/install-external-secrets-operator': 'https://docs.kuberocketci.io/docs/operator-guide/secrets-management/install-external-secrets-operator',
  'operator-guide/external-secrets-operator-integration': 'https://docs.kuberocketci.io/docs/operator-guide/secrets-management/external-secrets-operator-integration',
  'operator-guide/overview-devsecops': 'https://docs.kuberocketci.io/docs/operator-guide/devsecops/overview',
  'operator-guide/install-velero': 'https://docs.kuberocketci.io/docs/operator-guide/disaster-recovery/install-velero',
  'operator-guide/restore-edp-with-velero': 'https://docs.kuberocketci.io/docs/operator-guide/disaster-recovery/velero-restore-platform',
  'operator-guide/install-loki': 'https://docs.kuberocketci.io/docs/operator-guide/monitoring-and-observability/install-loki',
  'operator-guide/multitenant-logging': 'https://docs.kuberocketci.io/docs/operator-guide/monitoring-and-observability/multitenant-logging',
  'operator-guide/schedule-pods-restart': 'https://docs.kuberocketci.io',
  'operator-guide/kibana-ilm-rollover': 'https://docs.kuberocketci.io/docs/operator-guide/monitoring-and-observability/kibana-ilm-rollover',
  'operator-guide/manage-custom-certificate': 'https://docs.kuberocketci.io/docs/operator-guide/advanced-installation/custom-certificates',
  'operator-guide/oauth2-proxy': 'https://docs.kuberocketci.io/docs/operator-guide/auth/oauth2-proxy',

  // Upgrade guides
  'operator-guide/upgrade-edp-3.9': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.9',
  'operator-guide/upgrade-edp-3.8': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.8',
  'operator-guide/upgrade-edp-3.7': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.7',
  'operator-guide/upgrade-edp-3.6': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.6',
  'operator-guide/upgrade-edp-3.5': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.5',
  'operator-guide/upgrade-edp-3.4': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.4',
  'operator-guide/upgrade-edp-3.3': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.3',
  'operator-guide/upgrade-edp-3.2': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.2',
  'operator-guide/upgrade-edp-3.1': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-edp-3.1',
  'operator-guide/upgrade-keycloak-19.0': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/upgrade-keycloak-19.0',
  'operator-guide/delete-edp': 'https://docs.kuberocketci.io/docs/operator-guide/uninstall-kuberocketci',
  'operator-guide/deploy-aws-eks': 'https://docs.kuberocketci.io/docs/operator-guide/deploy-aws-eks',
  'operator-guide/deploy-okd': 'https://docs.kuberocketci.io/docs/operator-guide/infrastructure-providers/okd/deploy-okd-4.9',
  'operator-guide/deploy-okd-4.10': 'https://docs.kuberocketci.io/docs/operator-guide/infrastructure-providers/okd/deploy-okd-4.10',
  'operator-guide/github-debug-webhooks': 'https://docs.kuberocketci.io/docs/user-guide/add-git-server',
  'operator-guide/install-kiosk': 'https://docs.kuberocketci.io',
  'operator-guide/migrate-ci-pipelines-from-jenkins-to-tekton': 'https://docs.kuberocketci.io/docs/operator-guide/upgrade/migrate-ci-pipelines-from-jenkins-to-tekton',
  'operator-guide/ssl-automation-okd': 'https://docs.kuberocketci.io/docs/operator-guide/infrastructure-providers/okd/ssl-automation-okd',
  'operator-guide/gitlab-debug-webhooks': 'https://docs.kuberocketci.io/docs/user-guide/add-git-server',
  'operator-guide/overview-sast': 'https://docs.kuberocketci.io/docs/operator-guide/devsecops/overview',
  'operator-guide/troubleshooting/troubleshoot-git-server': 'https://docs.kuberocketci.io/docs/user-guide/add-git-server',
  'operator-guide/edp-kiosk-usage': 'https://docs.kuberocketci.io',

  // Quick start guides
  'quick-start/quick-start-overview': 'https://docs.kuberocketci.io/docs/quick-start/quick-start-overview',
  'quick-start/platform-installation': 'https://docs.kuberocketci.io/docs/quick-start/platform-installation',
  'quick-start/integrate-sonarcloud': 'https://docs.kuberocketci.io/docs/quick-start/integrate-sonarcloud',
  'quick-start/integrate-github': 'https://docs.kuberocketci.io/docs/quick-start/integrate-github',
  'quick-start/integrate-container-registry': 'https://docs.kuberocketci.io/docs/quick-start/integrate-container-registry',
  'quick-start/create-application': 'https://docs.kuberocketci.io/docs/quick-start/create-application',
  'quick-start/integrate-argocd': 'https://docs.kuberocketci.io/docs/quick-start/integrate-argocd',
  'quick-start/deploy-application': 'https://docs.kuberocketci.io/docs/quick-start/deploy-application',
  // User guide redirects
  'user-guide/cd-pipeline-details': 'https://docs.kuberocketci.io/docs/user-guide/add-cd-pipeline',
  'user-guide/code-review-pipeline': 'https://docs.kuberocketci.io/docs/user-guide/tekton-pipelines',
  'user-guide/prepare-for-release': 'https://docs.kuberocketci.io/docs/developer-guide',
  'user-guide/build-pipeline': 'https://docs.kuberocketci.io/docs/user-guide/tekton-pipelines',
  'user-guide/marketplace': 'https://docs.kuberocketci.io/docs/user-guide/marketplace',
  'user-guide/add-marketplace': 'https://docs.kuberocketci.io/docs/user-guide/add-marketplace',
  'user-guide/components': 'https://docs.kuberocketci.io/docs/user-guide/components',
  'user-guide/application': 'https://docs.kuberocketci.io/docs/user-guide/application',
  'user-guide/add-application': 'https://docs.kuberocketci.io/docs/user-guide/add-application',
  'user-guide/autotest': 'https://docs.kuberocketci.io/docs/user-guide/autotest',
  'user-guide/add-autotest': 'https://docs.kuberocketci.io/docs/user-guide/add-autotest',
  'user-guide/library': 'https://docs.kuberocketci.io/docs/user-guide/library',
  'user-guide/add-library': 'https://docs.kuberocketci.io/docs/user-guide/add-library',
  'user-guide/infrastructure': 'https://docs.kuberocketci.io/docs/user-guide/infrastructure',
  'user-guide/add-infrastructure': 'https://docs.kuberocketci.io/docs/user-guide/add-infrastructure',
  'user-guide/manage-branches': 'https://docs.kuberocketci.io/docs/user-guide/manage-branches',
  'user-guide/add-cd-pipeline': 'https://docs.kuberocketci.io/docs/user-guide/add-cd-pipeline',
  'user-guide/manage-environments': 'https://docs.kuberocketci.io/docs/user-guide/manage-environments',
  'user-guide/add-quality-gate': 'https://docs.kuberocketci.io/docs/use-cases/autotest-as-quality-gate',
  'user-guide/configuration-overview': 'https://docs.kuberocketci.io/docs/user-guide/configuration-overview',
  'user-guide/quick-links': 'https://docs.kuberocketci.io/docs/user-guide/quick-links',
  'user-guide/git-server-overview': 'https://docs.kuberocketci.io/docs/user-guide/git-server-overview',
  'user-guide/add-cluster': 'https://docs.kuberocketci.io/docs/user-guide/add-cluster',
  'user-guide/cluster': 'https://docs.kuberocketci.io/docs/user-guide/cluster',
  'user-guide/gitops': 'https://docs.kuberocketci.io/docs/user-guide/gitops',
  'user-guide/manage-container-registries': 'https://docs.kuberocketci.io/docs/user-guide/manage-container-registries',
  'user-guide/cicd-overview': 'https://docs.kuberocketci.io/docs/developer-guide/reference-cicd-pipeline',
  'user-guide/terraform-stages': 'https://docs.kuberocketci.io/docs/operator-guide/ci/ci-pipeline-terraform',
  'user-guide/opa-stages': 'https://docs.kuberocketci.io/docs/about-platform',
  'user-guide/helm-stages': 'https://docs.kuberocketci.io/docs/operator-guide/ci/tekton-overview',
};
